### ISSUE TITLE
Meta-issue to surface samples, cross-link between prose topics and source code

### ISSUE THREAD

**Issue by BillWagner** [dotnet/core-docs#586]
There are a few issues with the samples we have written for this repository.

- [x] They are not surfaced with appropriate prominence in the TOC
- [x] Many of the samples do not have a readme.md. The readme.md should briefly describe the project, and link to the prose topic for more details.
- [x] The prose topics should have a prominent link to the code. Suggested text "Get the code". Suggested location: As a highlighted div at the top of the article.

The attached file contains the list of all samples, and notes about where the topic is located in the repo.

@richlander Let's discuss and I'll start working on this one.

**List of all projects in the core-dos repository:**

_Three projects that make up the detailed step-by-step instructions
Referenced from ./docs/getting-started/cli-console-app-tutorial.md_
./samples/core-projects/console-apps/NewTypes/global.json
./samples/core-projects/console-apps/NewTypes/src/NewTypes/project.json
./samples/core-projects/console-apps/NewTypes/test/NewTypesTests/project.json
./samples/core-projects/console-apps/Fibonacci/project.json
./samples/core-projects/console-apps/FibonacciBetter/project.json
./samples/core-projects/console-apps/Hello/project.json
./samples/core-projects/console-apps/HelloNative/project.json
./samples/core-projects/libraries/new-library/global.json
./samples/core-projects/libraries/new-library/src/DependencyLibrary/project.json
./samples/core-projects/libraries/new-library/src/Library/project.json
./samples/core-projects/libraries/new-library/test/LibraryTests/project.json

_Maps to creating libraries with the CLI: docs/core-concepts/libraries-with-cli.md._
./samples/core-projects/libraries/frameworks-library/src/Library/project.json
./samples/core-projects/libraries/net40-library/src/Library/project.json
./samples/core-projects/libraries/net45-compat-library/src/Library/project.json
./samples/core-projects/libraries/pcl-library/src/Library/project.json

_Used in the Getting Started with Testing sample.
Referenced from docs/core-concepts/testing/unit-testing-with-dotnet-test.md_ 
./samples/unit-testing/using-dotnet-test/global.json
./samples/unit-testing/using-dotnet-test/src/PrimeService/project.json
./samples/unit-testing/using-dotnet-test/test/PrimeService.Tests/project.json

**All four of these are for the "getting started with C# section.
Main page is ./docs/tutorials/getting-started-with-chsarp/index.md**

_This is ./docs/tutorials/getting-started-with-csharp/console-linq.md_
./docs/tutorials/getting-started-with-csharp/console-linq/project.json
_ This is ./docs/tutorials/getting-started-with-csharp/console-teleprompter.md_
./docs/tutorials/getting-started-with-csharp/console-teleprompter/project.json
_This_ is ./docs/tutorials/getting-started-with-csharp/console-web-apiclient.md_
./docs/tutorials/getting-started-with-csharp/console-webapiclient/project.json
_This is ./docs/tutorials/getting-started-with-csharp/microservices.md_
./docs/tutorials/getting-started-with-csharp/WeatherMicroservice/project.json

_./docs/languages/csharp/delegates-events.md_
./samples/csharp-language/delegates-and-events/project.json
./samples/csharp-language/events/project.json

_./docs/languages/csharp/expression-trees.md_
./samples/csharp-language/expression-trees/project.json

_./docs/languages/csharp/indexers.md_
./samples/csharp-language/indexers/project.json

_./docs/languages/csharp/iterators.md_
./samples/csharp-language/iterators/project.json

_These are all updates of the '101 LINQ samples'
that were created for C# 3, .NET 3.5.
There is a readme.md in the ./samples directory,
but it for earlier betas, and does not provide any guidance on each sample._
./samples/linq/csharp/aggregate/project.json
./samples/linq/csharp/concatenation/project.json
./samples/linq/csharp/conversion/project.json
./samples/linq/csharp/customsequence/project.json
./samples/linq/csharp/element/project.json
./samples/linq/csharp/equality/project.json
./samples/linq/csharp/generation/project.json
./samples/linq/csharp/grouping/project.json
./samples/linq/csharp/join/project.json
./samples/linq/csharp/ordering/project.json
./samples/linq/csharp/partitioning/project.json
./samples/linq/csharp/projection/project.json
./samples/linq/csharp/quantifier/project.json
./samples/linq/csharp/queryexecution/project.json
./samples/linq/csharp/restriction/project.json
./samples/linq/csharp/setoperators/project.json

**Comment by BillWagner** [comment]
After some discussions, here is the proposal:

1.       The /samples folder will contain all the sample code. The /samples folder will contain folders that match the top level folders from the doc's TOC.
2.       Every sample will have a readme.md that (where applicable) will point back to the prose that describes the sample.
3.       The ‘samples’ node in the main TOC is more of a list or index of all samples. This list will have pointers to both the prose (elsewhere under docs) and the code (under /samples) for each sample that has been created. (Note: We're still gathering feedback on whether the samples.md file should contain links to prose as well as code, or only the code. Please weigh in in the comments.)
4.       Every topic with an accompanying sample will have a link to get the code at the start of the topic.

This will generate 4 PRs:

- [ ] Create / Update Readme.md in each sample.
- [ ] Move all samples to the correct location (see above.)
- [ ] Update .md files to point at the appropriate sample.
- [ ] create /docs/samples.md
